name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.
publish_to: "none"

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_blue: ^0.7.2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
